# Use the Bitnami Spark base image
FROM bitnami/spark:3.2.1

# Switch to root to install additional packages
USER root

# Set the Spark master URL environment variable
ENV SPARK_MASTER_URL=spark://spark-master:7077

# Install Python, pip, and wget
RUN apt-get update && \
    apt-get install -y python3 python3-pip wget && \
    rm -rf /var/lib/apt/lists/*

# Install and upgrade Python packages
RUN pip3 install --upgrade pip && \
    pip3 install --upgrade numpy && \
    pip3 install Flask pandas pyarrow

# Install Iceberg
ENV ICEBERG_VERSION=0.13.1
RUN wget https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.2_2.12/${ICEBERG_VERSION}/iceberg-spark-runtime-3.2_2.12-${ICEBERG_VERSION}.jar -O /opt/bitnami/spark/jars/iceberg-spark-runtime-3.2_2.12-${ICEBERG_VERSION}.jar

# Switch back to the non-root user
USER 1001

# Default command
CMD ["/opt/bitnami/scripts/spark/entrypoint.sh"]